version: '3.9'
services:
    web:
        image: nginx
        ports:
            - "8000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
    customer:
        image: bookstore_baseimage:latest
        environment:
            - APP_ROOT=/customers
        volumes:
            - ./customer:/app/base
            - ./db/customers.db:/app/database.db
    inventory:
        image: bookstore_baseimage:latest
        environment:
            - APP_ROOT=/inventory
        volumes:
            - ./inventory:/app/base
            - ./db/inventory.db:/app/database.db
    order:
        image: bookstore_baseimage:latest
        environment:
            - APP_ROOT=/orders
        volumes:
            - ./order:/app/base
            - ./db/orders.db:/app/database.db
networks:
    default:
        name: bookstore